# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='XXX', max_length=5),
        ),
    ]
