# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0002_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
