# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0005_game_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='default_score_away',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='default_score_home',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
