# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0006_auto_20170617_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score_away',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_home',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='default_score_away',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='default_score_home',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
