# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0008_auto_20170617_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='typer.Group'),
            preserve_default=False,
        ),
    ]
