# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0009_bet_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typer.Game')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='is_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupgame',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typer.Group'),
        ),
    ]
