# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0010_auto_20170623_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='points',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
