# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0011_bet_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bonus', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typer.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bet',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='membergroup',
            name='default_score_away',
        ),
        migrations.RemoveField(
            model_name='membergroup',
            name='default_score_home',
        ),
        migrations.AddField(
            model_name='bet',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
