# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0013_auto_20170628_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='votes',
        ),
        migrations.AddField(
            model_name='votes',
            name='voter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
