# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 12:52
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0014_auto_20170629_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTeamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='bets_per_round',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='defaultteamgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typer.Group'),
        ),
        migrations.AddField(
            model_name='defaultteamgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typer.Team'),
        ),
    ]
