# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0015_auto_20170705_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField()),
                ('season', models.SmallIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typer.Team')),
            ],
        ),
    ]
